version: "3.8"

services:
  backend:
    image: backend-app:latest
    container_name: backend-container
    ports:
      - "8000:5000"
    env_file:
      - .env   # relative path, points to .env in repo root
    restart: always